### ISSUE TITLE
RGBA Point Opacity Issue

### ISSUE THREAD

**Issue by simonwarchol** [flekschas/regl-scatterplot#74]
Hey Fritz,

When moving from `0.14.0` to `1.1.0` I noticed the alpha values when setting `pointColor` or `pointColorActive` with a RGBA color (e.g. `pointColorActive: [ 1, 0.6470588235294118, 0, 0.2]`) the alpha values are being overwritten with `1` 
I was able to fix this for `pointColor` by setting opacity to `NaN`, which gets around 
`!Array.isArray(opacity) && Number.isNaN(+opacity)`

Not sure how to fix it for pointColorActive, it seems like the textures are getting created correctly.

Let me know if you have any ideas. Also, the Density-based opacity encoding is really great!

-Simon

**Comment by flekschas** [comment]
Do you have a small test case or example handy I could look at? From your description this very much sounds like a bug and should not happen.

**Comment by simonwarchol** [comment]
Totally,

https://codesandbox.io/embed/agitated-ives-4fyqp?fontsize=14&hidenavigation=1&theme=dark

Let me know if you have issues accessing.

**Comment by flekschas** [comment]
Thanks! This helps. The bug seems to be related to the initialization. When you append `scatterplot.set({ opacity: 0.1 });` the opacity is applied as expected. (That's also why I haven't noticed it.) I'll investigate.

**Comment by flekschas** [comment]
I found the source of the issue. In the short term you can get around the issue by specifying the opacity explicitly during initialization:

```js
onst scatterplot = createScatterplot({
  pointColor: [0, 0, 0, 0.1],
  opacity: 0.1,
});
```

The issue is related to the fact that the opacity can be specified either via `pointColor` or `opacity`. The default value of `opacity` for initialization is `1`, which causes the `pointColor` alpha value to be ignored. Introducing a special `auto` value as the `opacity`'s initial value should fix the issue.

I'll try to get to it in the next week. If you need it sooner please feel free to set up a PR. I am happy to merge it.

**Comment by simonwarchol** [comment]
Hey Fritz,

Sounds good -- I've made a fork of the repo and played around a little bit and think I mostly understand the `pointColor` issue, which seems to be fixed if I update line 89 of the point vertex shader from 
`color.a = min(1.0, texture2D(encodingTex, opacityTexIndex).y + globalState);` to 
`color.a = min(min(1.0, texture2D(encodingTex, opacityTexIndex).y + globalState), color.a);` such that the alpha value isn't always overwritten if it's set on the color. However, I'm having a harder time tracking down where the `pointColorActive` alpha value is being disregarded. Will take another look in the next few days.
-Simon

**Comment by flekschas** [comment]
Hi Simon,

I don't think we need to change the shader for the general point opacity.

`color.a = min(min(1.0, texture2D(encodingTex, opacityTexIndex).y + globalState), color.a);` could lead to wrong results. For instance, when the globalState demands a more opaque point (e.g., on hover or when being selected), the color's alpha value would override this.

Instead, I believe we need to first change the default value of the opacity from `1` to a special value that I would call `auto`. The current default value of `1` is overriding of the RGBA's alpha value. If instead the default value is `auto` then on initialization the logic could be: _If the opacity is `auto` and `pointColor` is a RGBA value then use the RGBA's alpha value as the opacity. If no RGBA value is provided and opacity is `auto` then set opacity to `1`. If `opacity` is not `auto` use whatever value opacity has._

I haven't yet looked into opacity issue of `pointColorActive`. Maybe the issue is more difficult there. It seems like `encodingTex` somehow does not store the active and hover opacities, which is probably why their opacities are ignored and always set to `1` in the shader. Do you remember if it worked before?

**Comment by flekschas** [comment]
@simonwarchol The issue should be fixed. Can you test if it's working for you again using the latest code on master?

**Comment by simonwarchol** [comment]
Hey @flekschas,
Amazing -- I've confirmed that setting the `pointColor` issue is fixed on master. It looks like it's still not possible to set opacity with `pointColorActive`, which i know did work in older versions. I was having trouble tracking down that bug when going through the repo but if you have any suggestions I can take a swing,
Thanks again,
Simon

**Comment by flekschas** [comment]
Mhh in my local tests I was able to set the opacity for `pointColorActive` but I might have missed a case. Could you post an example setup? That'd help to get to the root of the issue.

**Comment by simonwarchol** [comment]
hmmm so it looks like the selected points are opaque relative to a black background, so the very transparent points in the example appear black. 

I feel like I'm doing something wrong :| 

```
const scatterplot = createScatterplot({
    canvas,
    width,
    height,
    pointSize: 5,
    pointColor: [0, 0, 0, 0.1],
    pointColorActive: [0.9, 0, 0, 0.00001],
    pointOutlineWidth: 0,
    pointSizeSelected: 0
});

const points = new Array(10000)
    .fill()
    .map(() => [-1 + Math.random() * 2, -1 + Math.random() * 2]);

scatterplot.draw(points);
```

**Comment by simonwarchol** [comment]
Hey Fritz,
I think what i'm seeing on my end is that with a white background, low opacity selected points are appearing as black as opposed to as invisible. Is this expected?
![image](https://user-images.githubusercontent.com/3915140/155395385-bae8a577-2c68-445f-a7fd-fd5143d76592.png)
Appreciate your patience here,
Simon

**Comment by flekschas** [comment]
Could it be that you haven't set `backgroundColor` to `[1, 1, 1, 1]`? By default the background color is assumed to be black. This influences selected points as selected points are actually drawn as three points (outline > inner border > point). The inner border is achieved by drawing the points with a slightly larger radius and color them according to `backgroundColor`.

**Comment by simonwarchol** [comment]
Hmm so if i set a backgroundColor doing the same, I now see the selected points in that background color
![image](https://user-images.githubusercontent.com/3915140/155400302-2a65eea5-668d-4406-8693-0591d859a919.png)
```
import createScatterplot from "regl-scatterplot";

const canvas = document.querySelector("#myCanvas");

const {width, height} = canvas.getBoundingClientRect();

const scatterplot = createScatterplot({
    canvas,
    width,
    height,
    pointSize: 5,
    pointColor: [0, 0, 0, 0.1],
    pointColorActive: [0.9, 0, 0, 0.00001],
    backgroundColor: [1, 0, 1, 1],
    pointOutlineWidth: 0,
    pointSizeSelected: 0
});

const points = new Array(10000)
    .fill()
    .map(() => [-1 + Math.random() * 2, -1 + Math.random() * 2]);

scatterplot.draw(points);
```

**Comment by flekschas** [comment]
Yeah so it's working as expected.

But I am sensing that you're expecting a different result here :) What are you expecting to see with the above setup?

**Comment by simonwarchol** [comment]
Lol ok sorry about that :/ so if I wanted a config where selected points disappeared entirely from the plot due to extremely low opacity, leaving only the un-selected points how would I accomplish this? (just a hypothetical, not a real use case, just trying to fully understand)

**Comment by simonwarchol** [comment]
as always, appreciate your help here

**Comment by simonwarchol** [comment]
Gotcha -- tried doing the following and I'm not seeing any difference setting a low alpha on the background color, so the example with pink background above looks the same with `backgroundColor: [1, 0, 1, 0],`. 

Ideally, I'd like to be able to select points without fully occluding the points that may lie behind these points. I suppose I could do this by adding a listener on select that instead redraws the points to two distinct `opacityBy` values based on if the points were in the selection or not.

What would you advise?

**Comment by flekschas** [comment]
I think the best approach to achieve this is as follows:

```js
const scatterplot = createScatterplot({
  canvas,
  showReticle: false,
  pointSize: 5,
  pointColor: [1, 1, 1, 0.33],
  pointColorHover: [0, 1, 0, 0.5],
  pointColorActive: [0, 1, 1, 0.33],
  pointSizeSelected: 0,
  pointOutlineWidth: 0,
  backgroundColor: [0, 0, 0, 0],
});
```

_Make sure to test this on the latest version of master as I fixed some more glitches related to zero opacities._

it should look as follows:

![Feb-23-2022 21-53-00](https://user-images.githubusercontent.com/932103/155448660-c3327930-8b0f-4952-bf3e-d56420e680a9.gif)

Is this what you had in mind?

Unfortunately, the selected points are always drawn twice (once as normal points and a second time for highlighting). That's also why you cannot make selected points disappear. You can only choose to not highlight them. Ideally the first drawing was omitted, but that requires a bit more refactoring of the library.

**Comment by simonwarchol** [comment]
Hey Fritz,
I think this is exactly what I'm looking for. Thank you! I think you forgot to push these changes to master, happy to test when you do.
Really appreciate it,
-Simon

**Comment by flekschas** [comment]
> I think you forgot to push these changes to master

Haha, thanks for pointing this out. I just pushed :)

Let me know if it works for you, then I can release a new version.

**Comment by simonwarchol** [comment]
Looks perfect! tysm
